/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { GreenCredit, GreenCreditInterface } from "../GreenCredit";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "issue",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalCredits",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b5060ed8061001e6000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c8063b5bd3eb9146037578063cc872b66146051575b600080fd5b603f60005481565b60405190815260200160405180910390f35b6060605c3660046079565b6062565b005b80600080828254607191906091565b909155505050565b600060208284031215608a57600080fd5b5035919050565b8082018082111560b157634e487b7160e01b600052601160045260246000fd5b9291505056fea264697066735822122080556b9541723a9ea86709d816b3fd78c4d4ef985e493e2b8b256801c61fe93764736f6c634300081c0033";

type GreenCreditConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: GreenCreditConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class GreenCredit__factory extends ContractFactory {
  constructor(...args: GreenCreditConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      GreenCredit & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): GreenCredit__factory {
    return super.connect(runner) as GreenCredit__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): GreenCreditInterface {
    return new Interface(_abi) as GreenCreditInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): GreenCredit {
    return new Contract(address, _abi, runner) as unknown as GreenCredit;
  }
}
